### PR TITLE
17 setup persistent eventstore

### PR DESCRIPTION
**Pull request by ELWOOD29**

### CODE REVIEW

**Comment by github1** [comment]
Is there a way to set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY values with this?

**Comment by github1** [comment]
The reason being for the above is if we wanted to use different accounts with specific limited permissions (e.g. one for Lex and one for DynamoDB).

**Comment by ELWOOD29** [comment]
Ahh right, so eventstore uses the aws-sdk and that pulls the access key id and secret access key from the environment config. I will have a look into how we could prevent it from doing this automatically

**Comment by ELWOOD29** [comment]
As I read yesterday, the norm when using multiple AWS services with different users is to do say:
```
const s3 = AWS.S3({region:"us-east-1", accessKeyId="1234..."});
const ec2 = AWS.EC2({region:"us-west-2", accessKeyId="5678..."});
```

so eventstore automatically pulling them from environment config could cause some issues

**Comment by github1** [comment]
Looks like we may just be able to pass that configuration into the hash based on https://github.com/adrai/node-eventstore/blob/21e0fbfb2dcd58b47c79500f82d770de2770181a/lib/databases/dynamodb.js#L39. It isn't documented but based on reading the code I think it will work.

**Comment by github1** [comment]
We can hold off for now

**Pull request merged**
